### PR TITLE
Added function to add admins

### PR DESCRIPTION
**Pull request by swornimbarahi**
### Description

Added a function to make admins using the custom claims feature of Firebase.

### Note

The purpose of this is to reduce the number of reads and writes and not have important functions like these in the frontend.

### CODE REVIEW

**Comment by gonzen2310** [comment]
> Please refactor the functions into separate files, and import them.

Bro, just double-checking. If I understood well, you want a file per function? I so, why would we do that if all of the functions are related?

**Comment by nthungdev** [comment]
> > Please refactor the functions into separate files, and import them.
> 
> Bro, just double-checking. If I understood well, you want a file per function? I so, why would we do that if all of the functions are related?

Please let me know how are sendNotification and makeAdmin related bro?

**Comment by gonzen2310** [comment]
> > > Please refactor the functions into separate files, and import them.
> > 
> > 
> > Bro, just double-checking. If I understood well, you want a file per function? I so, why would we do that if all of the functions are related?
> 
> Please let me know how are sendNotification and makeAdmin related bro? I meant functions in index.ts, not anonymous functions in makeAdmin

they both depend on admin.initializeApp({ . . . })

**Comment by swornimbarahi** [comment]
> > > Please refactor the functions into separate files, and import them.
> > 
> > 
> > Bro, just double-checking. If I understood well, you want a file per function? I so, why would we do that if all of the functions are related?
> 
> Please let me know how are sendNotification and makeAdmin related bro? I meant functions in index.ts, not anonymous functions in makeAdmin

Bro they both use the same firebase admin sdk though

**Comment by nthungdev** [comment]
> 
> they both depend on admin.initializeApp({ . . . })

Yes, they depend on admin.initializeApp({ . . . }) running before they are invoked, which doesn't mean they can't be in separate files.

> 
> Bro they both use the same firebase admin sdk though

Yes, they use firebase admin SDK to perform the goal of the function, but they do completely 2 different functionalities, correct?

I didn't factor sendNotification into separate file before because it is the only function at the time (helloWorld is not counted). But since we have a second one now and potentially more in the future. It's good to not put everything in index file.

**Comment by gonzen2310** [comment]
> > they both depend on admin.initializeApp({ . . . })
> > Bro they both use the same firebase admin sdk though
> 
> Yes, they depend on admin.initializeApp({ . . . }) running before they are invoked, which doesn't mean they can't be in separate files.
> 
> Both of them utilize firebase admin SDK, but they do completely 2 different functionalities, correct?
> 
> I didn't factor sendNotification into separate file before because it was the only function at the time (helloWorld is not counted). But since we have a second one now and potentially more in the future. It's good to not put everything in index file.

In that case, we should remove all of the functions in index.ts and put them into a namespaced file like admin, notifications, etc and then import them into index.ts

**Comment by nthungdev** [comment]
> 
> In that case, we should remove all of the functions in index.ts and put them into a namespaced file like admin, notifications, etc and then import them into index.ts

That's is what I am trying to say in the first place 😄 btw, I would name it something like Role instead of admin namespace so it won't be confused with admin the SDK

**Pull request merged**
